version: '3.8'

services:
  # --- PostgreSQL service ---
  postgres:
    image: postgres:14
    container_name: d2t_postgres
    environment:
      - POSTGRES_USER=Dorian
      - POSTGRES_PASSWORD=tqy4468
      - POSTGRES_DB=d2t_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
    # --- Go backend service ---
  go-backend:
    build: ./be-server
    container_name: go_service
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      # 这里注入数据库连接信息给 Go 应用
      DB_HOST: localhost
      DB_PORT: "5432"
      DB_USER: Dorian
      DB_PASS: tqy4468
      DB_NAME: d2t_db
volumes:
  pgdata:
